### ISSUE TITLE
Adding composer package manager

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-php5#11]
I'm going to look into adding composer for the WordPress role soon. I see that `debops.nodejs` comes with npm. I was wondering if it made sense to have it here as well. Ansible [supports it](http://docs.ansible.com/ansible/composer_module.html) as well.

The issue is that there doesn't seem to be an maintained [Debian package for it](https://github.com/composer/composer/issues/1811). [This one](https://github.com/engineyard/php-composer) seems alright, but no updates in the last 6 months. In fact using a package isn't in the recommended [installation method](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx) either.

So yeah, not sure if it makes sense to you to have it in `debops.php5`. That said, it's a pretty important part of the PHP ecosystem at this point. I feel it makes sense.

**Comment by drybjed** [comment]
First of all, doing `curl | php` installation is unacceptable to me because of lack of authentication. `.deb` packages downloaded from an APT repository can be authenticated using GPG keys, and the same cannot be said about piping some random commands to a command interpreter. For more info, you can find a draft of [DebOps Software Policy](https://wiki.debops.org/wiki:software-policy) on the wiki, perhaps we could move that to the official docs at some point.

However, there is another solution. A [composer package is present in Debian Strech archive](https://packages.debian.org/stretch/composer), and making a backport to Jessie is a viable way to install it. Official backports obviously require a maintainer, but first you would need to check if backporting the package will succeed. If so, I bet that many more people will be interested in it, so uploading the result to official [Debian Backports](http://backports.debian.org/) repository might be benefical.

**Comment by drybjed** [comment]
Just noticed that [the composer package might be removed from testing soon](https://packages.qa.debian.org/c/composer.html), so I wonder how that will go...

**Comment by carlalexander** [comment]
Yeah, that's what I figured with the `curl`installation. I hope the guy fixes it for the backports. I guess for now I'll handle this by hand. I'll reopen it when we can install it in a safe manner.
