### ISSUE TITLE
Is there any roadmap for adding php 7?

### ISSUE THREAD

**Issue by MatthewMi11er** [debops/ansible-php5#12]

**Comment by drybjed** [comment]
[PHP7 package](https://packages.debian.org/stretch/php7.0) is currently included in Debian Stretch. I think that for official support in DebOps it should be at least backported to Jessie (no idea if it's viable right now). If you want, you could try building the `php7.0` packages on Jessie and checking if they work. [Mixing packages from Stable and other releases might lead to breakage](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian) so I wouldn't do that.

DebOps officially is focused on Debian Stable distribution. I haven't yet tried running it on Debian Stretch, and I'll probably look at it somewhere around Testing freeze. [The freeze date hasn't been planned yet](https://release.debian.org/stretch/freeze_policy.html) but I suspect it will be somewhere around November 2016, about two years after Jessie freeze.

I'm not sure about compatibility between PHP5 and PHP7 in regards for the applications. Probably going with a separate Ansible role to manage it would be best. I saw an effort in Debian to allow installation of PHP5 and PHP7 packages at the same time, but that's probably designed for Stretch, not Jessie.

**Comment by drybjed** [comment]
You can read the [PHP7 transition notes](https://lists.debian.org/debian-devel-announce/2016/01/msg00002.html) for more information about PHP7 support in Debian.

**Comment by MatthewMi11er** [comment]
Thanks, I'll read up on that. I'm not in any hurry at this point, mostly curious. 

I definitely think it makes the most sense to have a separate role.

**Comment by carlalexander** [comment]
PHP 7 is now the default PHP version for Xenial in April. Is the plan to make a separate package for it?

**Comment by drybjed** [comment]
@carlalexander Can PHP5 applications work with PHP7 installed? In Debian there are plans to support both at the same time so I imagine that there are some incomatibilities... So going with a separate role seems better, rather than shoehorning the new version here.

**Comment by carlalexander** [comment]
I think it's wiser to make a separate role. You target `php5` packages anyways so it's safe as long as the versions are supported. I think a `php7` role makes sense here.

As far as incompatibilities, there aren't any per say outside the usual deprecated stuff. HHVM has compatibility issues because it's a different engine and Facebook added support for their own programming language hack. There's none of that with php7. It's just a different compiling engine, but it's compatible with PHP5 (as long as you don't use anything deprecated).

**Comment by drybjed** [comment]
Great. Separate role will also not mess with Debian Jessie, which currently doesn't have any PHP7 packages as far as I know (outside of dotdeb and similar solutions). Maybe backports will be available in the future, but I wouldn't cross my fingers.

**Comment by mbarcia** [comment]
Upon a quick look, there isn't much to do than renaming a few packages from php5- to php7-. 

Problem is the name of the current role "php5". So, I'd start working on a "php" role fork, that would keep backwards compatibility with PHP5... just my 2 cents. I may have time available to help as well. Cheers.

**Comment by carlalexander** [comment]
There are cases (like WordPress) where you want both. So it's important that either the role support both or that we keep both version in separate packages. That said, there's also a lot of overlap so not sure how to handle that in a sane way.

**Comment by mbarcia** [comment]
Then I'd break the task into smaller milestones.
1. Have php7 and php5 (working separately)
2. Have them working at the same time

2. I'm not sure, could you please provide more info about the use case in
Wordpress? Thank you.

**Comment by carlalexander** [comment]
The reason for the need for PHP 5 is that the WordPress minimum required PHP version is PHP 5.2. Now, WordPress itself is compatible with PHP 7, but the minimum version requirement means that plugins and themes don't have to be. 

This means that to safely use PHP 7 with WordPress, you need a way to failover to PHP 5 if a plugin or theme is somewhat incompatible.

**Comment by drybjed** [comment]
From my perspective, there's a very small chance that PHP7 will be officially supported in Debian Jessie, so having separate PHP7 role makes more sense and gives better flexibility. Freeze for Debian Stretch will happen in 2017, so we have some time to make the role. I suppose there are DotDeb packages, but I'm not sure about the quality and support.

**Comment by mbarcia** [comment]
@carlalexander "failover to PHP5"? I've never heard of such a thing. In Debian Jessie, you get PHP 5.6, so if any plugin in your Wordpress site is incompatible with PHP 5.6: don't you need to use Debian Wheezy? (I've never looked into configuring PHP's latest version instead of the stable) I think what you want is the new role to keep/maintain backwards compatibility with PHP5. Thus, this newly proposed 'php' role would install and configure one version or the other, depending on the variables you pass to the role in a playbook.

@drybjed In my case, I'd be targeting Ubuntu Xenial, not Debian Jessie. Ubuntu latest LTS ships with php7 (and excludes php5). Is Ubuntu Xenial to be supported by debops? I'd expect so.

**Comment by drybjed** [comment]
@mbarcia My focus with DebOps is on [current Debian Stable release](https://wiki.debops.org/wiki:software-policy), which at the moment is Debian Jessie. Ubuntu is supported on a "best effort" basis, mostly because Travis-CI uses Ubuntu Precise for tests. Note that Ubuntu bases its releases on Debian Testing and Unstable branches, not Debian Stable.

Debian Stretch freeze is planned around [February 2017](https://release.debian.org/stretch/freeze_policy.html). Due to the DebOps packages entering Debian Archive, and me wanting to support Debian Stretch out of the box, I'll probably check the comatibility of various roles like `debops.ifupdown` and others with Stretch and fix any issues as time allows.

**Comment by mbarcia** [comment]
@drybjed I understand, thanks for the clarification. PHP7 is still young but Feb 2017 seems a bit too far away in time. To fill the gap and start enjoying all the new stuff of PHP7, I'd fork ansible-php5 role (for Xenial) and contribute it back, in time for Stretch.

Talking now about Debian Jessie: suppose it starts supporting PHP7... in the summer (just a guess). So the packages for php7 would need to come from the jessie backports repository right? Would that be supported by the current ansible-php5 role?

PS: It would be nice to have dotdeb's php7 packages in the new "php" fork, so Jessie gets PHP7 for development and benchmarking.

**Comment by drybjed** [comment]
Yes, with current Software Policy PHP7 packages should come from `jessie-backports` repository, although [that seems unlikely](https://www.reddit.com/r/debian/comments/4hkyo2/any_chance_of_php7_in_jessiebackports/) due to an additional affort required for backporting. It looks like developers want to focus on polishing packages for Stretch release, and I don't blame them. 

You could try [backporting the packages yourself](https://wiki.debian.org/SimpleBackportCreation) from Debian Testing to Jessie to see how much work it takes. And if you succeed and feel like supporting the backported packages be you is a good idea, you can then [upload them to jessie-backports](http://backports.debian.org/Contribute/) so that your efforts can benefit others.

I haven't touched PHP7 then, not sure about differences between it and PHP5. I imagine that if they are on scale of say MySQL vs MariaDB, ie. full compatibility with previous version, then `debops.php5` role could be rewritten to support both versions at once, especially if applications can cope with switch between PHP5 and PHP7 without issues.

I try not to use repositories other than Debian Archive and upstream, due to a possibility of creating [FrankenDebian](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian). In any case, such possibility should be optional and it needs to be specifically enabled by the user (see MariaDB/PostgreSQL support in DebOps as an example).

**Comment by mbarcia** [comment]
Here's my work so far:
https://github.com/debops/ansible-php5/compare/master...mbarcia:DRUPSIBLE-208?expand=1

Features:
* Kept current PHP5 support in Jessie
* Added support for PHP 7.0 in Xenial
* Added support for PHP 5.6 in Xenial (that can coexist with PHP 7.0)
* Added ansible local fact for PHP-FPM version, so other roles can read it

Comments (from the top of my head):
* Renamed role to debops.php. Also files internally, from php5 to php.
* Package names must NOT include php*- prefix
* Variables renamed from php5_* to php__*
* php5_flag renamed to php__flags
* php5_admin_flag renamed to php__admin_flags
* php5_value renamed to php__values
* php5_admin_value renamed to php__admin_values

On way to test: add this to requirements.yml:
```
- src: https://github.com/mbarcia/ansible-php5
  version: remotes/origin/DRUPSIBLE-208
  name: debops.php
```

The support for 5.6 in Xenial is experimental, didn't test it thoroughly. PHP 7.0 tested with a vanilla Drupal and working so far.

Other observations:
* PEAR is included php7.0-cli and php5.6-cli
* Twig C extension is not available, but it may not be needed
* uploadprogress extension is not available in PHP 7.0

Have a nice weekend!

**Comment by mbarcia** [comment]
Update:
- Package names MAY include php*- prefix, ie. php-soap for PHP5 is not prefixed like all the others (should be php5-soap). But if you want just leave the prefix out, and debops.php will match it automatically with the PHP-FPM version.
- Tested on Jessie 8.4 (which now comes with PHP 5.6) and Xenial (7.0). Testing PHP 5.6 on Xenial as I write this.
- correction: PHP5.6 and PHP7.0 can be installed, but not actually co-exist (unless manually installed). debops.php will install one or another.

On another note, unrelated to this role, but related to the PHP world, uploadprogress package for PHP7 is available through Andrej's PPA.

**Comment by drybjed** [comment]
@mbarcia Looks better and better. :-) Any chance to provide some examples of package names that are prefixed, just to see how it would look like?

I don't have time at the moment to check your role more throughly, however I might do that soon. If it's a drop-in replacement for `debops.php5`, would most likely include it in main project as `debops.php`, and then switch other roles that use old `debops.php5` to the new dependency, after making sure everything works. Looking forward to it. :-) Also, thanks for making sure that various Debian releases work correctly. Any plans to check Stretch or Wheezy as well?

**Comment by mbarcia** [comment]
@drybjed glad to hear it. 

First things first, this debops.php role should be 100% compatible with debops.php5, so it should work as you mentioned, as a drop-in replacement for debops.php5.

The "automatic pkg prefix" thing is a magic sauce I've added to write less code in Drupsible with only a regexp in debops.php. 

It's okay if you don't know this as a user, because if you list the packages literally it will work as usual.

So as a client of this role, Drupsible has these variables ("smart mode"):
```
...
php__packages:
- php-pear
- php-soap
- gmp
- mysql
...
```
and the role playbook executes like this on Ubuntu Xenial:
```
TASK [debops.php : Add Ondřej Surý PPA key] ************************************
skipping: [localhost]

TASK [debops.php : Add Ondřej Surý PPA repository] *****************************
skipping: [localhost]

TASK [debops.php : Make sure PHP-FPM support is installed] *********************
changed: [localhost] => (item=[u'php7.0-fpm', u'php7.0-cli'])

TASK [debops.php : Make sure that Ansible local facts directory is present] ****
ok: [localhost]

TASK [debops.php : Save PHP-FPM local facts] ***********************************
changed: [localhost]

TASK [debops.php : Gather facts if they were modified] *************************
skipping: [localhost]

TASK [debops.php : Install PHP packages] ***************************************
changed: [localhost] => (item=[u'php-pear', u'php-soap', u'php7.0-gmp', u'php7.0-mysql', u'php7.0-curl', u'php7.0-gd', u'php7.0-mcrypt'])
```
PEAR and SOAP packages are not prefixed properly like the others, so you have to force the prefix. The other packages don't need the prefix set explicitely, but if you include it it will work. For example, the [current PHP package list](https://github.com/mbarcia/drupsible-project/blob/master/ansible/inventory/group_vars.default/app_name/deploy.yml#L117-L121) in clients of the current debops.php5 are set like this ("explicit mode"):
```
...
php__packages:
- php-pear
- php-soap
- php5-gmp
- php5-mysql
...
```
and debops.php will work just as debops.php5.

There's no need to specify/force php__version, unless you're on Xenial and need PHP 5.6. In that case, force php__version in the role client vars, 
```php__version: '5.6'```

and you will get this
```
TASK [debops.php : Add Ondřej Surý PPA key] ************************************
changed: [localhost]

TASK [debops.php : Add Ondřej Surý PPA repository] *****************************
changed: [localhost]

TASK [debops.php : Make sure PHP-FPM support is installed] *********************
changed: [localhost] => (item=[u'php5.6-fpm', u'php5.6-cli'])

TASK [debops.php : Make sure that Ansible local facts directory is present] ****
ok: [localhost]

TASK [debops.php : Save PHP-FPM local facts] ***********************************
changed: [localhost]

TASK [debops.php : Gather facts if they were modified] *************************
skipping: [localhost]

TASK [debops.php : Install PHP packages] ***************************************
changed: [localhost] => (item=[u'php-pear', u'php-soap', u'php5.6-gmp', u'php5.6-mysql', u'php5.6-curl', u'php5.6-gd', u'php5.6-mcrypt'])
```

In "smart mode" you don't need to change the package list across distros. Thus, on Debian Jessie (or Wheezy), php__version would be automatically set to '5', pkg prefixes will be added automatically, and debops.php playbook would run like this:
```
TASK [debops.php : Add Ondřej Surý PPA key] ************************************
skipping: [localhost]

TASK [debops.php : Add Ondřej Surý PPA repository] *****************************
skipping: [localhost]

TASK [debops.php : Make sure PHP-FPM support is installed] *********************
changed: [localhost] => (item=[u'php5-fpm', u'php5-cli'])

TASK [debops.php : Make sure that Ansible local facts directory is present] ****
ok: [localhost]

TASK [debops.php : Save PHP-FPM local facts] ***********************************
changed: [localhost]

TASK [debops.php : Gather facts if they were modified] *************************
skipping: [localhost]

TASK [debops.php : Install PHP packages] ***************************************
changed: [localhost] => (item=[u'php-pear', u'php-soap', u'php5-gmp', u'php5-mysql', u'php5-curl', u'php5-gd', u'php5-mcrypt'])
```

I will look for Wheezy and Stretch boxes and test those as well, hopefully today.

**Comment by mbarcia** [comment]
Wheezy crashed on Ansible installation. Tried a box for Stretch but it hanged upon startup (Setting hostname...).

**Comment by thiagotalma** [comment]
@mbarcia How is the work on this improvement?
I'm watching anxiously. If you need any help you can count on me.

@drybjed, in his opinion, there is still much work to be possible to apply the debops?

**Comment by mbarcia** [comment]
Hi @thiagotalma I've committed this to Drupsible, so it should be ready.
https://github.com/mbarcia/ansible-php
Please test, thank you in advance.

**Comment by drybjed** [comment]
I'm back from vacation in a few days. I plan to fork the above repo, update
it a bit and merge into DebOps core, after that other roles will be
switched over.
17 cze 2016 18:30 "Mariano Barcia" <notifications@github.com> napisał(a):

**Comment by thiagotalma** [comment]
@drybjed Excellent news!

**Comment by mbarcia** [comment]
Just so know, I've rebased my master fork and updated php.ini to php7.0. I've also created a symlink for the cli to use the same INI. Check it out! Thanks.

**Comment by thiagotalma** [comment]
I'm anxious... :laughing:

**Comment by drybjed** [comment]
@thiagotalma Oh, I'm sorry. New role is up - [debops.php](https://github.com/debops/ansible-php/). It's also available through Ansible Galaxy and is included in DebOps playbook.

**Comment by thiagotalma** [comment]
:clap: :clap: :clap: :clap: 

@drybjed @mbarcia great work, guys!
Congratulations!
